name: Test and Deploy

# when this action runs
on:
  push:
    branches:
      - main

# what to do
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo 'Howdy doodle from CI'

      - name: say bye
        run: cho 'laterzzz'
