name: Test and Deploy

# when this action runs
on:
  push:
    branches:
      - main

# what to do
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo 'Howdy doodle from CI'

      - name: say bye
        run: echo 'laterzzz'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone the repo
        uses: actions/checkout@v2

      - name: Setup database
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: edgey-games
          postgresql user: edgey
          postgresql password: gethacked

      - name: Install dependencies
        run: npm i

      - name: Run utils tests
        run: npm t utils

      - name: Run app tests
        run: PGDATABASE=edgey-games PGUSER=edgey PGPASSWORD=gethacked npm t app
