name: Test & Deploy

# When this action runs
on:
  push:
    branches:
      - main

# Setup and test phase
jobs:
  test:
    name: Setup and test everything
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.1.0

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: "test_db"
          postgresql user: "test_user"
          postgresql password: "test_password"

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: PGDATABASE=test_db PGUSER=test_user PGPASSWORD=test_password npm t

  ## Deploy to Heroku phase
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_API_KEY }}
